version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "16001:16001" # Adjust port as needed for your backend
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - backend

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - backend

volumes:
  node_modules:
  redis-data:


networks:
  backend:
